esphome:
  name: announcement-test
  friendly_name: announcement-test

esp32:
#  board: esp32-s3-devkitc-1
  board: tinypico
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zN1Esdage6+TGVdOhMgqwp/voecu+sfrqEjI068lpX4="

ota:
  - platform: esphome
    password: "10f8cf5f730ce4e0aa5e0a8b24e23294"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "announcement-test"
    password: "kk8bjVTYTXqT"

captive_portal:

web_server:
  port: 80

prometheus:

i2s_audio:
  i2s_lrclk_pin: GPIO27
  i2s_bclk_pin: GPIO26

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: GPIO25
    mode: mono


# http://nrk-mms-live.telenorcdn.net:80/nrk_radio_jazz_mp3_h


# stereo output:
# https://community.home-assistant.io/t/i2s-esp32-stereo-output-two-max98357a/573741
# UPDATE: Figured out stereo output. Problem was in MAX98357A configuration. By default it is configured to mix outputs using 1M resistor (to VDD) so to configure it to left and right channels, SD needs to be pulled-up to VDD with jumper (0 Ohms) that is going to be LEFT channel and with 370-470K resistor to VDD to output Right channel.
