esphome:
  name: announcement-test
  friendly_name: announcement-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zN1Esdage6+IGVdOhMgqwp/voecu+sfrqEjI068lpX4="

ota:
  - platform: esphome
    password: "10f8cf5f730ce4e0aa5e0a8b24e23294"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "announcement-test"
    password: "kk8bjVTYTXqT"

captive_portal:

web_server:
  port: 80
