esphome:
  name: doorbell-chime-hallway
  friendly_name: doorbell-chime-hallway
  on_boot:
    priority: -100  # Lower priority ensures WiFi is ready
    then:
      - delay: 3s
      - media_player.volume_set: 5%
      - media_player.play_media: !lambda return id(startup_sound_url).state.c_str();
      - wait_until:
          condition:
            media_player.is_playing: i2s_media_player
      - wait_until:
          condition:
           media_player.is_idle: i2s_media_player
      - media_player.volume_set: 90%

# https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto/652601/8
#psram:
#  mode: octal
#  speed: 80MHz

esp32:
  board: tinypico
  framework:
    type: arduino

logger:
#  level: VERY_VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # esp32 needs the output_power setting, see https://github.com/espressif/arduino-esp32/issues/2144#issuecomment-2028949116
  output_power: 8.5dB

web_server:
  port: 80

prometheus:

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

#status_led:
# https://help.unexpectedmaker.com/index.php/knowledge-base/esphome-with-tinypico-apa-rgb-led/
# cool idea for the rgb led: https://github.com/esphome/esphome/pull/5814:

i2s_audio:
  i2s_lrclk_pin: GPIO27
  i2s_bclk_pin: GPIO26

media_player:
  - platform: i2s_audio
    id: i2s_media_player
    name: Media Player
    dac_type: external
    i2s_dout_pin:
      number: GPIO25

text:
  - platform: template
    name: "Startup Sound URL"
    id: startup_sound_url
    icon: mdi:link-variant
    initial_value: "http://intercom-iot.local/static/sbb-1chan-44100.wav"
    restore_value: false
    optimistic: true
    mode: text
  - platform: template
    name: "Doorbell Sound URL"
    id: doorbell_sound_url
    icon: mdi:link-variant
    initial_value: "http://intercom-iot.local/static/doorbell-1chan-44100.wav"
    restore_value: false
    optimistic: true
    mode: text


button:
  - platform: template
    id: doorbell_button
    name: Doorbell
    icon: "mdi:bell"
    on_press:
      - media_player.play_media: !lambda return id(doorbell_sound_url).state.c_str();
