esphome:
  name: hobby-room-climate
  friendly_name: hobby-room-climate

# https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto/652601/8
psram:
  mode: octal
  speed: 80MHz

esp32:
  board: esp32-s3-devkitc-1
#  board: seeed_xiao_esp32s3
  framework:
    type: arduino
#    type: esp-idf  # wifi connection problems with esp-idf :/
  flash_size: 8MB

logger:
#  level: VERY_VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: none

web_server:
  port: 80

prometheus:

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true

sensor:
  - platform: scd4x
    co2:
      name: "Hobby Room CO2"
    temperature:
      name: "Hobby Room Temperature"
    humidity:
      name: "Hobby Room Humidity"
    update_interval: 5s

status_led:
  pin:
    number: GPIO21  #LED_BUILTIN
    inverted: true
