esphome:
  name: hobby-room-climate
  friendly_name: hobby-room-climate

# https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto/652601/8
psram:
  mode: octal
  speed: 80MHz

esp32:
  board: seeed_xiao_esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

logger:
#  level: VERY_VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # esp32 needs the output_power setting, see https://github.com/espressif/arduino-esp32/issues/2144#issuecomment-2028949116
  output_power: 8.5dB

web_server:
  port: 80

prometheus:

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

  - platform: scd4x
    co2:
      name: "Hobby Room CO2"
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 15
    temperature:
      name: "Hobby Room Temperature"
    humidity:
      name: "Hobby Room Humidity"
    update_interval: 5s

status_led:
  pin:
    number: GPIO21  #LED_BUILTIN
    inverted: true
