esphome:
  name: sprinkler-control
  friendly_name: sprinkler-control

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

logger:
#  level: VERY_VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # esp32 needs the output_power setting, see https://github.com/espressif/arduino-esp32/issues/2144#issuecomment-2028949116
  output_power: 8.5dB

web_server:
  port: 80

prometheus:

# relay 0 (main)  D7
# relay 1         D6      (greenhouse/gravel garden)
# relay 2         D5      (greenhouse/gravel garden)
# relay 3         GPIO9   (hedge/rose garden)
# relay 4         GPIO10  (hedge/rose garden)
# relay 5         D2
# relay 6         D1      (front altan)
# relay 7         D0

switch:
  - platform: gpio
    id: switch_valve_main
    name: "Main"
    icon: "mdi:valve"
    pin: D7
    inverted: true
    on_turn_off:
      then:
        - switch.turn_off: switch_valve_hedge
        - switch.turn_off: switch_valve_gazebo
        - switch.turn_off: switch_valve_gravel_garden

  - platform: gpio
    id: switch_valve_hedge
    name: "Hedge"
    icon: "mdi:sprinkler"
    pin: GPIO9
    inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch_valve_main
    on_turn_off:
      then:
        - if:
            condition:
              and:
                - switch.is_off: switch_valve_gazebo
                - switch.is_off: switch_valve_gravel_garden
            then:
              - switch.turn_off: switch_valve_main

  - platform: gpio
    id: switch_valve_gazebo
    name: "Gazebo"
    icon: "mdi:sprinkler"
    pin: D5
    inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch_valve_main
    on_turn_off:
      then:
        - if:
            condition:
              and:
                - switch.is_off: switch_valve_hedge
                - switch.is_off: switch_valve_gravel_garden
            then:
              - switch.turn_off: switch_valve_main

  - platform: gpio
    id: switch_valve_gravel_garden
    name: "Gravel Garden"
    icon: "mdi:sprinkler"
    pin: GPIO9
    inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch_valve_main
    on_turn_off:
      then:
        - if:
            condition:
              and:
                - switch.is_off: switch_valve_hedge
                - switch.is_off: switch_valve_gazebo
            then:
              - switch.turn_off: switch_valve_main
