# thank you https://www.printables.com/model/1167457-1u-rack-mount-wopr-leds-enclosure

esphome:
  name: storage-room-fan
  friendly_name: Storage Room Fan Control

# https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto/652601/8
psram:
  mode: octal
  speed: 80MHz

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

logger:
  level: WARN

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 8.5dB

web_server:
  port: 80

prometheus:

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

  - platform: dht
    pin: GPIO8
    temperature:
      name: "Storage Room Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Storage Room Humidity"
      accuracy_decimals: 0
    update_interval: 120s

  - platform: pulse_counter
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
    name: Storage Fan Speed
    id: fan_speed_tacho
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    update_interval: 2s

status_led:
  pin:
    number: GPIO21  # LED_BUILTIN
    inverted: true

output:
  - platform: ledc
    id: fan_speed_control
    pin: GPIO7
    frequency: "25000 Hz"
    min_power: 1%
    max_power: 100%

fan:
  - platform: speed
    output: fan_speed_control
    name: Storage Room Fan
