# thank you https://www.printables.com/model/1167457-1u-rack-mount-wopr-leds-enclosure

esphome:
  name: storage-room-fan
  friendly_name: Storage Room Fan Control

globals:
  - id: automation_running
    type: bool
    initial_value: 'false'
  - id: co2_threshold_low
    type: float
    initial_value: '450.0'
  - id: co2_threshold_high
    type: float
    initial_value: '3500.0'

# https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto/652601/8
psram:
  mode: octal
  speed: 80MHz

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

logger:
  level: WARN

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 8.5dB

web_server:
  port: 80

prometheus:

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
  id: i2c_bus

output:
  - platform: ledc
    id: fan_speed_control
    pin: GPIO7
    frequency: "25000 Hz"
    min_power: 1%
    max_power: 100%

fan:
  - platform: speed
    output: fan_speed_control
    name: "Storage Room Fan"
    id: storage_fan

    on_speed_set:
      # If speed is adjusted manually and we aren't in 'Auto',
      # the automation will effectively stay 'off' because we check the preset.
      then:
        - if:
            condition:
              lambda: 'return !id(automation_running);'
            then:
              - switch.turn_on: fan_manual_override

switch:
  - platform: template
    name: "Fan Manual Override"
    id: fan_manual_override
    optimistic: true
    restore_mode: ALWAYS_OFF
    entity_category: config
    on_turn_on:
      then:
        - delay: 30min
        - switch.turn_off: fan_manual_override

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

  - platform: scd4x
    i2c_id: i2c_bus
    co2:
      name: "Storage Room CO2"
      id: storage_room_co2
      on_value:
        then:
          - if:
              condition:
                switch.is_off: fan_manual_override
              then:
                - lambda: 'id(automation_running) = true;'
                - if:
                    condition:
                      lambda: 'return x <= id(co2_threshold_low);'
                    then:
                      - fan.turn_off: storage_fan
                    else:
                      - fan.turn_on:
                          id: storage_fan
                          speed: !lambda |-
                            if (x >= id(co2_threshold_high)) return 100;
                            return (int)((x - id(co2_threshold_low)) / (id(co2_threshold_high) - id(co2_threshold_low)) * 100.0);
                - lambda: 'id(automation_running) = false;'
    temperature:
      name: "Storage Room Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Storage Room Humidity"
      accuracy_decimals: 1

  - platform: pulse_counter
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
    name: Storage Fan Speed
    id: fan_speed_tacho
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    update_interval: 2s

status_led:
  pin:
    number: GPIO21  # LED_BUILTIN
    inverted: true
